# Generated by Django 4.1 on 2022-09-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_tag_notas_note_notas_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Notas',
            new_name='tag',
        ),
    ]
